### ISSUE TITLE
Build failure with GHC 9.2.1

### ISSUE THREAD

**Issue by sjakobi** [stschiff/sequence-formats#3]
```
src/SequenceFormats/Utils.hs:76:41: error:
    • Couldn't match type: forall x' x.
                           Pipes.Internal.Proxy x' x () PB.ByteString m0 ()
                     with: Pipes.Internal.Proxy
                             Pipes.Internal.X () () PB.ByteString m ()
      Expected: GHC.IO.Handle.Types.Handle
                -> Pipes.Internal.Proxy Pipes.Internal.X () () PB.ByteString m ()
        Actual: GHC.IO.Handle.Types.Handle
                -> Pipes.Core.Producer' PB.ByteString m0 ()
    • In the third argument of ‘PS.withFile’, namely ‘PB.fromHandle’
      In the expression: PS.withFile f ReadMode PB.fromHandle
      In an equation for ‘readFileProd’:
          readFileProd f = PS.withFile f ReadMode PB.fromHandle
    • Relevant bindings include
        readFileProd :: FilePath -> Producer PB.ByteString m ()
          (bound at src/SequenceFormats/Utils.hs:76:1)
   |
76 | readFileProd f = PS.withFile f ReadMode PB.fromHandle
   |                                         ^^^^^^^^^^^^^
cabal: Failed to build sequence-formats-1.6.1
```

**Comment by sjakobi** [comment]
The same error affects v1.3.1 and presumably all versions since – at least they don't build with GHC 9.0.1.

It would be good to add constraints `base < 4.15` so constraint-solver based tools like `cabal` won't attempt to build these versions with GHC >= 9. Would you mind if I use my Hackage trustee powers to apply such constraints?

**Comment by stschiff** [comment]
Thank you. Yes please, feel free to add this. I'm mostly using `stack`, for which I haven't noticed an error of this kind. Have not yet upgraded to GHC 9, though.

**Comment by stschiff** [comment]
Umm... now I'm confused. Do we still need #4 then? I think I need a bit to understand this properly...

**Comment by sjakobi** [comment]
#4 will make this package compatible with GHC 9.0.1 and 9.2.1.

The mentioned additional constraints are to inform users and build tools that v1.6.1 and older are _incompatible_ with GHC >= 9 (due to the error mentioned in the issue description).

Meanwhile, I have added these constraints in the form of Hackage revisions. See e.g. https://hackage.haskell.org/package/sequence-formats-1.6.1/revisions/.

**Comment by stschiff** [comment]
OK, I think I get it. But if we now put in a constraint, how would that help folks who install an old version that doesn't yet have that constraint? From my perspective, thanks to your PR we have now made this package compatible with newer GHCs, but the old ones remain incompatible, and unfortunately I can't change hackage retrospectively, can I?
